version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: excel-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: af016d37e830 # TODO: Use custom compose on production
      MONGO_INITDB_DATABASE: excel-viewer
    volumes:
      - mongo-data:/data/db
    networks:
      - excel-network

  backend:
    build: ./backend
    container_name: excel-viewer-backend
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - ./backend/.env.docker
    depends_on:
      - mongo
    networks:
      - excel-network

  frontend:
    build: ./frontend
    container_name: excel-viewer-frontend
    restart: always
    ports:
      - "5173:80"
    env_file:
      - ./frontend/.env.docker
    depends_on:
      - backend
    networks:
      - excel-network

volumes:
  mongo-data:

networks:
  excel-network:
    driver: bridge
